# Generated by Django 3.0 on 2019-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191213_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='Q', upload_to='images/'),
        ),
    ]
