# Generated by Django 3.0 on 2019-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191213_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
